"""Canonical event names defined by docs/event-catalog.md."""

from __future__ import annotations

EVENT_NAMES: tuple[str, ...] = (
    "tenant.provisioned.v1",
    "tenant.entitlement.updated.v1",
    "identity.user.provisioned.v1",
    "identity.user.role.assigned.v1",
    "lead.created.v1",
    "lead.assignment.updated.v1",
    "lead.converted.v1",
    "lead.conversion.failed.v1",
    "contact.created.v1",
    "contact.merged.v1",
    "account.created.v1",
    "account.hierarchy.updated.v1",
    "opportunity.created.v1",
    "opportunity.stage.changed.v1",
    "opportunity.closed.v1",
    "quote.created.v1",
    "quote.submitted_for_approval.v1",
    "approval.requested.v1",
    "approval.decided.v1",
    "quote.accepted.v1",
    "order.created.v1",
    "subscription.created.v1",
    "subscription.status.changed.v1",
    "invoice.summary.updated.v1",
    "payment.event.recorded.v1",
    "campaign.created.v1",
    "campaign.activated.v1",
    "campaign.completed.v1",
    "case.created.v1",
    "case.sla.breached.v1",
    "case.sla.first_response_breached.v1",
    "case.sla.resolution_breached.v1",
    "case.resolved.v1",
    "communication.message.sent.v1",
    "communication.message.engagement.updated.v1",
    "notification.dispatched.v1",
    "notification.failed.v1",
    "knowledge.article.published.v1",
    "workflow.execution.completed.v1",
    "workflow.execution.failed.v1",
    "search.document.upserted.v1",
    "feature_flag.updated.v1",
    "audit.log.recorded.v1",
    "eventbus.dead_lettered.v1",
    "job.enqueued.v1",
    "job.started.v1",
    "job.succeeded.v1",
    "job.retry.scheduled.v1",
    "job.failed.v1",
    "job.dead_lettered.v1",
    "schedule.created.v1",
    "schedule.updated.v1",
    "schedule.deleted.v1",
    # Partner channel management events
    "partner.created.v1",
    "partner.relationship.activated.v1",
    "partner.deal.registered.v1",
    "partner.deal.approved.v1",
    "partner.deal.rejected.v1",
    "partner.attribution.locked.v1",
    "partner.commission.calculated.v1",
    "partner.commission.approved.v1",
    "partner.commission.paid.v1",
    "partner.tier_changed.v1",
    "partner.status_changed.v1",
    # Campaign send tracking events
    "campaign.paused.v1",
    "campaign.cancelled.v1",
    "campaign.send.queued.v1",
    "campaign.send.delivered.v1",
    "campaign.send.read.v1",
    "campaign.send.replied.v1",
    "campaign.send.failed.v1",
    "campaign.conversion.attributed.v1",
    # Contact opt-out
    "contact.opted_out.v1",
    # AI scoring & copilot events
    "ai.lead_scored.v1",
    "ai.churn_predicted.v1",
    "ai.clv_estimated.v1",
    "ai.suggestion_generated.v1",
    "ai.suggestion_dismissed.v1",
    "ai.suggestion_actioned.v1",
    "ai.query_answered.v1",
)

EVENT_NAME_SET: frozenset[str] = frozenset(EVENT_NAMES)
